Repository HKanwal/kapstone, pull requests merged in 2022-11, with the labels that each got.

#49 Add Rev 0 of VnV Plan
  docs/VnVPlan/VnVPlan.pdf
  docs/VnVPlan/VnVPlan.tex
Labels: documentation

#35 Add User Models + API Endpoints for Shop Owner Login System
  src/django-app/README.md
  src/django-app/django-project/accounts/__init__.py
  src/django-app/django-project/accounts/admin.py
  src/django-app/django-project/accounts/apps.py
  src/django-app/django-project/accounts/migrations/0001_initial.py
  src/django-app/django-project/accounts/migrations/__init__.py
  src/django-app/django-project/accounts/models.py
  src/django-app/django-project/accounts/serializers.py
  src/django-app/django-project/accounts/signals.py
  src/django-app/django-project/accounts/tests.py
  src/django-app/django-project/accounts/views.py
  src/django-app/django-project/config/settings.py
  src/django-app/django-project/config/urls.py
  src/django-app/requirements.txt
Labels: back end

#39 Shop owner login and registration
  src/next-app/.eslintrc.json
  src/next-app/.gitignore
  src/next-app/components/BackButton.tsx
  src/next-app/components/Button.tsx
  src/next-app/components/Chip.tsx
  src/next-app/components/DropdownField.tsx
  src/next-app/components/EmailsField.tsx
  src/next-app/components/Header.tsx
  src/next-app/components/Link.tsx
  src/next-app/components/Modal.tsx
  src/next-app/components/TextField.tsx
  src/next-app/components/TextInput.tsx
  src/next-app/components/TextMultiField.tsx
  src/next-app/package.json
  src/next-app/pages/create-account.tsx
  src/next-app/pages/create-shop.tsx
  src/next-app/pages/example-page.tsx
  src/next-app/pages/index.tsx
  src/next-app/pages/invite.tsx
  src/next-app/pages/login.tsx
  src/next-app/public/fallback-development.js
  src/next-app/public/sw.js
  src/next-app/public/sw.js.map
  src/next-app/public/workbox-eac1af49.js
  src/next-app/public/workbox-eac1af49.js.map
  src/next-app/styles/Home.module.css
  src/next-app/styles/components/BackButton.module.css
  src/next-app/styles/components/Button.module.css
  src/next-app/styles/components/Chip.module.css
  src/next-app/styles/components/DropdownField.module.css
  src/next-app/styles/components/EmailsField.module.css
  src/next-app/styles/components/Header.module.css
  src/next-app/styles/components/Link.module.css
  src/next-app/styles/components/Modal.module.css
  src/next-app/styles/components/TextField.module.css
  src/next-app/styles/components/TextInput.module.css
  src/next-app/styles/components/TextMultiField.module.css
  src/next-app/styles/globals.css
  src/next-app/styles/pages/CreateAccount.module.css
  src/next-app/styles/pages/CreateShop.module.css
  src/next-app/styles/pages/Home.module.css
  src/next-app/styles/pages/Invite.module.css
  src/next-app/styles/pages/Login.module.css
  src/next-app/tsconfig.json
  src/next-app/utils/validateEmail.ts
  src/next-app/yarn.lock
Labels: front end

#53 Django: Add User Details API + Fix Employee Creation Serializer
  src/django-app/django-project/accounts/serializers.py
  src/django-app/django-project/accounts/signals.py
  src/django-app/django-project/accounts/urls.py
  src/django-app/django-project/accounts/views.py
  src/django-app/django-project/config/settings.py
  src/django-app/django-project/config/urls.py
  src/django-app/django-project/shops/__init__.py
  src/django-app/django-project/shops/admin.py
  src/django-app/django-project/shops/apps.py
  src/django-app/django-project/shops/migrations/0008_invitation.py
  src/django-app/django-project/shops/migrations/0009_alter_invitation_invitation_key.py
  src/django-app/django-project/shops/migrations/0010_alter_invitation_unique_together.py
  src/django-app/django-project/shops/models.py
  src/django-app/django-project/shops/serializers.py
  src/django-app/django-project/shops/signals.py
  src/django-app/django-project/shops/templates/invitations/email/employee_invitation.html
  src/django-app/django-project/shops/templates/invitations/email/employee_invitation.txt
  src/django-app/django-project/shops/urls.py
  src/django-app/django-project/shops/views.py
Labels: back end

#52 Add quote + quote request model, relevent APIs
  src/django-app/django-project/config/settings.py
  src/django-app/django-project/config/urls.py
  src/django-app/django-project/quotes/__init__.py
  src/django-app/django-project/quotes/admin.py
  src/django-app/django-project/quotes/apps.py
  src/django-app/django-project/quotes/migrations/0001_initial.py
  src/django-app/django-project/quotes/migrations/0002_alter_quote_status.py
  src/django-app/django-project/quotes/migrations/0003_quoterequest_shop_quoterequest_user.py
  src/django-app/django-project/quotes/migrations/__init__.py
  src/django-app/django-project/quotes/models.py
  src/django-app/django-project/quotes/serializers.py
  src/django-app/django-project/quotes/tests.py
  src/django-app/django-project/quotes/urls.py
  src/django-app/django-project/quotes/views.py
Labels: back end

#55 Next App: Shop owner dashboard w/ Navbar
  .vscode/settings.json
  src/next-app/components/Navbar.tsx
  src/next-app/components/ProfileModal.tsx
  src/next-app/constants/NavbarData.tsx
  src/next-app/pages/dashboard.tsx
  src/next-app/styles/components/Navbar.module.css
  src/next-app/styles/components/ProfileModal.module.css
  src/next-app/styles/pages/Dashboard.module.css
  src/next-app/tsconfig.json
Labels: front end

#60 Django: Better Error Handling for Rest Endpoints
  src/django-app/django-project/config/settings.py
  src/django-app/requirements.txt
Labels: bug, back end

#64 Django: Fix shop creation endpoint
  src/django-app/django-project/shops/serializers.py
Labels: bug, back end

#58 54 integrate login/registration with backend
  src/django-app/.gitignore
  src/django-app/django-project/config/settings.py
  src/django-app/requirements.txt
  src/next-app/components/Header.tsx
  src/next-app/constants/api-url.ts
  src/next-app/package.json
  src/next-app/pages/_app.tsx
  src/next-app/pages/create-account.tsx
  src/next-app/pages/create-shop.tsx
  src/next-app/pages/index.tsx
  src/next-app/pages/invite.tsx
  src/next-app/pages/login.tsx
  src/next-app/styles/pages/Login.module.css
  src/next-app/utils/api.ts
  src/next-app/yarn.lock
Labels: full stack

#72 Update api url to digital ocean deployment
  src/next-app/constants/api-url.ts
Labels: front end

#70 Django: Fix Repository Structure
  src/django-app/README.md
  src/django-app/accounts/__init__.py
  src/django-app/accounts/admin.py
  src/django-app/accounts/apps.py
  src/django-app/accounts/migrations/0001_initial.py
  src/django-app/accounts/migrations/0002_alter_user_managers.py
  src/django-app/accounts/migrations/0003_employeedata_shop.py
  src/django-app/accounts/migrations/__init__.py
  src/django-app/accounts/models.py
  src/django-app/accounts/serializers.py
  src/django-app/accounts/signals.py
  src/django-app/accounts/tests.py
  src/django-app/accounts/urls.py
  src/django-app/accounts/views.py
  src/django-app/config/__init__.py
  src/django-app/config/asgi.py
  src/django-app/config/settings.py
  src/django-app/config/urls.py
  src/django-app/config/wsgi.py
  src/django-app/manage.py
  src/django-app/quotes/__init__.py
  src/django-app/quotes/admin.py
  src/django-app/quotes/apps.py
  src/django-app/quotes/migrations/0001_initial.py
  src/django-app/quotes/migrations/0002_alter_quote_status.py
  src/django-app/quotes/migrations/0003_quoterequest_shop_quoterequest_user.py
  src/django-app/quotes/migrations/__init__.py
  src/django-app/quotes/models.py
  src/django-app/quotes/serializers.py
  src/django-app/quotes/tests.py
  src/django-app/quotes/urls.py
  src/django-app/quotes/views.py
  src/django-app/requirements.txt
  src/django-app/shops/__init__.py
  src/django-app/shops/admin.py
  src/django-app/shops/apps.py
  src/django-app/shops/migrations/0001_initial.py
  src/django-app/shops/migrations/0002_alter_shop_availability_alter_shop_num_bays_and_more.py
  src/django-app/shops/migrations/0003_rename_shophours_shop_shop_hours.py
  src/django-app/shops/migrations/0004_shop_name.py
  src/django-app/shops/migrations/0005_alter_shop_name.py
  src/django-app/shops/migrations/0006_alter_address_province.py
  src/django-app/shops/migrations/0007_remove_shop_num_employees.py
  src/django-app/shops/migrations/0008_invitation.py
  src/django-app/shops/migrations/0009_alter_invitation_invitation_key.py
  src/django-app/shops/migrations/0010_alter_invitation_unique_together.py
  src/django-app/shops/migrations/__init__.py
  src/django-app/shops/models.py
  src/django-app/shops/serializers.py
  src/django-app/shops/signals.py
  src/django-app/shops/templates/invitations/email/employee_invitation.html
  src/django-app/shops/templates/invitations/email/employee_invitation.txt
  src/django-app/shops/tests.py
  src/django-app/shops/urls.py
  src/django-app/shops/views.py
  src/django-app/static/.keep
Labels: back end

#76 Better forms
  src/next-app/components/Button.tsx
  src/next-app/hooks/useForm.ts
  src/next-app/pages/create-account.tsx
  src/next-app/pages/create-shop.tsx
  src/next-app/pages/login.tsx
Labels: front end
