Repository HKanwal/kapstone, pull requests merged in 2022-10, with the labels that each got.

#29 Update SRS.tex
  docs/SRS/SRS.pdf
  docs/SRS/SRS.tex
Labels: documentation

#16 13 initialize front end project
  .gitignore
  src/README.md
  src/next-app/.eslintrc.json
  src/next-app/.gitignore
  src/next-app/README.md
  src/next-app/next.config.js
  src/next-app/package.json
  src/next-app/pages/_app.tsx
  src/next-app/pages/_offline.tsx
  src/next-app/pages/api/hello.ts
  src/next-app/pages/example-page.tsx
  src/next-app/pages/index.tsx
  src/next-app/public/fallback-development.js
  src/next-app/public/favicon.ico
  src/next-app/public/icons/android-chrome-192x192.png
  src/next-app/public/icons/favicon-16x16.png
  src/next-app/public/icons/favicon-32x32.png
  src/next-app/public/icons/icon-512x512.png
  src/next-app/public/manifest.json
  src/next-app/public/sw.js
  src/next-app/public/sw.js.map
  src/next-app/public/vercel.svg
  src/next-app/public/workbox-eac1af49.js
  src/next-app/public/workbox-eac1af49.js.map
  src/next-app/styles/Home.module.css
  src/next-app/styles/globals.css
  src/next-app/tsconfig.json
  src/next-app/yarn.lock
Labels: front end

#32 Add ERD to repository
  docs/Django-App/Sayyara ERD.pdf
Labels: documentation

#20 Django App Setup
  src/django-app/.gitignore
  src/django-app/README.md
  src/django-app/django-project/config/__init__.py
  src/django-app/django-project/config/asgi.py
  src/django-app/django-project/config/settings.py
  src/django-app/django-project/config/urls.py
  src/django-app/django-project/config/wsgi.py
  src/django-app/django-project/manage.py
  src/django-app/requirements.txt
Labels: back end
