Repository HKanwal/kapstone, pull requests merged in 2023-03, with the labels that each got.

#108 107 employee pages
  src/next-app/components/EmployeeCard.tsx
  src/next-app/constants/NavbarData.tsx
  src/next-app/data/employeeData.json
  src/next-app/pages/employees/[id].tsx
  src/next-app/pages/employees/index.tsx
  src/next-app/styles/components/EmployeeCard.module.css
  src/next-app/styles/pages/CreateEmployee.module.css
  src/next-app/styles/pages/EmployeeDetails.module.css
  src/next-app/styles/pages/Employees.module.css
Labels: front end

#166 Cypress Tests: Employee and Work Order pages
  src/django-app/shops/migrations/0027_workorder_is_visible_to_customer.py
  src/django-app/shops/migrations/0028_alter_shop_shop_owner.py
  src/django-app/shops/models.py
  src/django-app/shops/policies.py
  src/django-app/shops/templates/workorders/email/workorder_email.html
  src/django-app/shops/templates/workorders/email/workorder_email.txt
  src/django-app/shops/views.py
  src/next-app/components/Button.tsx
  src/next-app/cypress.config.ts
  src/next-app/cypress/e2e/employees.cy.ts
  src/next-app/cypress/e2e/workorders.cy.ts
  src/next-app/cypress/support/commands.ts
  src/next-app/pages/employees/index.tsx
  src/next-app/pages/invite.tsx
  src/next-app/pages/login.tsx
  src/next-app/pages/work-orders/[id].tsx
  src/next-app/pages/work-orders/index.tsx
  src/next-app/styles/globals.css
Labels: testing

#160 Cypress Tests: quote requests, quotes, shop profile, employees
  src/next-app/components/Card.tsx
  src/next-app/components/Dropdown.tsx
  src/next-app/components/IconButton.tsx
  src/next-app/components/Navbar.tsx
  src/next-app/components/TextArea.tsx
  src/next-app/cypress/e2e/employees.cy.ts
  src/next-app/cypress/e2e/quote.cy.ts
  src/next-app/cypress/e2e/quoterequests.cy.ts
  src/next-app/cypress/e2e/shopProfile.cy.ts
  src/next-app/cypress/support/commands.ts
  src/next-app/pages/employees/[id].tsx
  src/next-app/pages/new-quote-requests/index.tsx
  src/next-app/pages/quote-request-details.tsx
  src/next-app/pages/quote-response.tsx
  src/next-app/pages/quote.tsx
  src/next-app/styles/components/QuoteRequestCard.module.css
  src/next-app/styles/pages/Quote.module.css
Labels: front end, testing

#167 jest tests
  .github/workflows/main.yml
  src/next-app/__tests__/Button.test.tsx
  src/next-app/__tests__/ButtonLink.test.tsx
  src/next-app/__tests__/Chip.test.tsx
  src/next-app/__tests__/Dropdown.test.tsx
  src/next-app/__tests__/FieldLabel.test.tsx
  src/next-app/__tests__/ShopResult.test.tsx
  src/next-app/jest.config.js
  src/next-app/jest.setup.js
  src/next-app/package.json
  src/next-app/stories/ButtonLink.stories.tsx
  src/next-app/tsconfig.json
  src/next-app/yarn.lock
Labels: front end, testing

#183 Add shop hours creation on Shop creation
  src/django-app/shops/views.py
Labels: back end

#176 Quote Comments + Desktop/Tablet styling of pages
  src/django-app/quotes/admin.py
  src/django-app/quotes/migrations/0011_quotecomment.py
  src/django-app/quotes/models.py
  src/django-app/quotes/policies.py
  src/django-app/quotes/serializers.py
  src/django-app/quotes/urls.py
  src/django-app/quotes/views.py
  src/next-app/components/CardComponents.tsx
  src/next-app/components/EditableTextArea.tsx
  src/next-app/components/IconButton.tsx
  src/next-app/components/Navbar.tsx
  src/next-app/pages/_app.tsx
  src/next-app/pages/create-shop.tsx
  src/next-app/pages/employees/[id].tsx
  src/next-app/pages/invitations.tsx
  src/next-app/pages/quote-request-details.tsx
  src/next-app/pages/quote.tsx
  src/next-app/pages/services/[id].tsx
  src/next-app/pages/services/create-service.tsx
  src/next-app/pages/services/index.tsx
  src/next-app/pages/shop/[id]/profile.tsx
  src/next-app/pages/work-orders/[id].tsx
  src/next-app/pages/work-orders/index.tsx
  src/next-app/styles/components/Button.module.css
  src/next-app/styles/components/Header.module.css
  src/next-app/styles/components/IconButton.module.css
  src/next-app/styles/components/Navbar.module.css
  src/next-app/styles/components/ProfileModal.module.css
  src/next-app/styles/globals.css
  src/next-app/styles/pages/CreateAccount.module.css
  src/next-app/styles/pages/CreateShop.module.css
  src/next-app/styles/pages/Dashboard.module.css
  src/next-app/styles/pages/EmployeeDetails.module.css
  src/next-app/styles/pages/Employees.module.css
  src/next-app/styles/pages/Home.module.css
  src/next-app/styles/pages/Invite.module.css
  src/next-app/styles/pages/Login.module.css
  src/next-app/styles/pages/NewQuoteRequests.module.css
  src/next-app/styles/pages/Quote.module.css
  src/next-app/styles/pages/QuoteRequestDetails.module.css
  src/next-app/styles/pages/ShopResults.module.css
Labels: full stack

#170 Block create shop page
  src/next-app/pages/create-shop.tsx
Labels: front end

#186 Appointment slot creation updates
  src/django-app/shops/management/commands/generate_appointment_slots.py
  src/django-app/shops/policies.py
  src/django-app/shops/views.py
Labels: back end

#189 Fix migrations merge conflict
  src/django-app/quotes/migrations/0012_merge_20230317_1930.py
Labels: bug, back end

#175 Post testing improvements
  src/next-app/components/EmployeeCard.tsx
  src/next-app/components/Header.tsx
  src/next-app/components/QuoteRequestCard.tsx
  src/next-app/pages/create-shop.tsx
  src/next-app/pages/employees/[id].tsx
  src/next-app/pages/employees/index.tsx
  src/next-app/pages/employees/shop-owner/[id].tsx
  src/next-app/pages/index.tsx
  src/next-app/pages/new-quote-requests/[id].tsx
  src/next-app/pages/new-quote-requests/index.tsx
  src/next-app/pages/quote-list.tsx
  src/next-app/pages/quote-request-details.tsx
  src/next-app/pages/quote-request-list.tsx
  src/next-app/pages/shop/[id]/profile.tsx
  src/next-app/styles/components/EmployeeCard.module.css
  src/next-app/styles/components/QuoteRequestCard.module.css
  src/next-app/styles/pages/EmployeeDetails.module.css
  src/next-app/styles/pages/NewQuoteRequests.module.css
  src/next-app/styles/pages/QuoteRequestList.module.css
Labels: front end

#194 Fix duplicate btns
  src/next-app/components/IconButton.tsx
Labels: front end

#178 Add shop owner appointment creation form page
  src/django-app/accounts/views.py
  src/django-app/vehicles/policies.py
  src/django-app/vehicles/serializers.py
  src/next-app/pages/create-appointment.tsx
Labels: full stack

#200 Shows newly created services in GET request
  src/django-app/shops/policies.py
Labels: back end

#199 Appointment Model Updates
  src/django-app/shops/migrations/0029_remove_workorder_quote_appointment_service_and_more.py
  src/django-app/shops/migrations/0030_alter_appointment_quote_alter_appointment_service_and_more.py
  src/django-app/shops/migrations/0031_appointment_either_provide_quote_or_service_not_both.py
  src/django-app/shops/models.py
  src/django-app/shops/serializers.py
  src/django-app/shops/signals.py
  src/django-app/shops/views.py
Labels: back end

#203 Appointment Schedule (Shop Owner)
  src/next-app/constants/NavbarData.tsx
  src/next-app/pages/appointment-schedule.tsx
  src/next-app/pages/book-appointment.tsx
  src/next-app/styles/components/Header.module.css
  src/next-app/styles/globals.css
  src/next-app/styles/pages/AppointmentSchedule.module.css
  src/next-app/utils/api.ts
Labels: front end

#173 Appointment details form
  src/next-app/pages/appointment-details.tsx
  src/next-app/styles/pages/QuoteRequestDetails.module.css
Labels: front end

#201 Aesthetic changes
  src/next-app/components/Navbar.tsx
  src/next-app/components/ProfileModal.tsx
  src/next-app/components/SmallButton.tsx
  src/next-app/pages/dashboard.tsx
  src/next-app/styles/components/Navbar.module.css
  src/next-app/styles/components/ProfileModal.module.css
  src/next-app/styles/components/SmallButton.module.css
Labels: front end

#80 Create "Find Shop" screen
  src/next-app/components/ShopResult.tsx
  src/next-app/constants/NavbarData.tsx
  src/next-app/pages/find-shop.tsx
  src/next-app/pages/quote-request.tsx
  src/next-app/pages/shop-results.tsx
  src/next-app/stories/ShopResults.stories.tsx
  src/next-app/styles/components/ShopResult.module.css
  src/next-app/styles/pages/Form.module.css
Labels: front end

#208 Update vehicle policies
  src/django-app/vehicles/policies.py
Labels: back end

#212 Fix most exhaustive deps warnings
  src/next-app/components/DropdownField.tsx
  src/next-app/components/TextInput.tsx
  src/next-app/pages/book-appointment.tsx
  src/next-app/pages/dashboard.tsx
  src/next-app/pages/find-shop.tsx
  src/next-app/pages/quote-request-list.tsx
Labels: front end

#220 bug fixes from demo
  src/next-app/components/BookedAppointment.tsx
  src/next-app/pages/appointment-details.tsx
  src/next-app/pages/appointment-schedule.tsx
  src/next-app/pages/booked-appointments.tsx
  src/next-app/pages/dashboard.tsx
  src/next-app/pages/employees/[id].tsx
  src/next-app/pages/new-quote-requests/[id].tsx
  src/next-app/pages/quote-list.tsx
  src/next-app/pages/quote-request-details.tsx
  src/next-app/pages/quote-request-list.tsx
  src/next-app/pages/quote-response.tsx
Labels: front end

#223 fixed quote request titles and sorted appointments
  src/next-app/pages/booked-appointments.tsx
  src/next-app/pages/new-quote-requests/[id].tsx
  src/next-app/pages/quote-request-details.tsx
  src/next-app/pages/quote-response.tsx
Labels: front end
